### ISSUE TITLE
Cookie change event access from Service Worker too

### ISSUE THREAD

**Issue by bsittler** [patrickkettner/cookie-change-events#32]
As currently described, cookie change events are inaccessible from [Service Worker](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/serviceworker/) as the Service Worker has no `document` and also has no persistent script execution environment to store the change event interest registration for the lifetime of the service worker registration. I think it would be better to extend any new API for cookie access to Service Workers too for [all the reasons motivating my own proposal](https://github.com/WICG/async-cookies-api/blob/gh-pages/explainer.md#motivations).

**Comment by patrickkettner** [comment]
totally agree that having access in there would be great. it is outside the scope of the current document, which is mostly aimed at giving people a straightforward way to use the existing API without having to poll it for changes. The benefit of this approach being that it is effectively already [implemented within extensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/onChanged).
