### ISSUE TITLE
Integration with RFC6265?

### ISSUE THREAD

**Issue by mikewest** [patrickkettner/cookie-change-events#39]
Do y'all need any hooks from the RFC we're in the process of poking at? It would be helpful to understand how we can explain this kind of thing to spec authors. Maybe calling out to your algorithms from the storage algorithms there?

**Comment by patrickkettner** [comment]
I'd be happy to be a guinea pig to figure out the best way to communicate. Not really sure what that would look like however. PRs welcomed :D
